spring.application.name=IncluLink
server.port=8081

#BASE DE DATOS (Postgres)
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL:url_de_tu_yugabyte_local}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tu_usuario_local}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tu_password_local}

spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

#HIKARI POOL
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.validation-timeout=5000

#HIBERNATE CONFIG
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.id.db_structure_naming_strategy=single
spring.jpa.defer-datasource-initialization=true

#SEGURIDAD (JWT)
app.jwt.secret=${APP_JWT_SECRET:claveSecretaLocalParaDesarrollo123456789}

#CLOUDINARY
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:cloudname_local}
cloudinary.api_key=${CLOUDINARY_API_KEY:apikey_local}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:apisecret_local}

#MULTIPART
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#CORREO
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from-name=IncluLink

spring.mail.username=${SPRING_MAIL_USERNAME:tu_correo_local@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:tu_clave_de_aplicacion_local}

#SWAGGER
springdoc.swagger-ui.path=/documentacion/swagger-ui.html
springdoc.paths-to-match=/api/v1/**
springdoc.packages-to-scan=com.inclulink.features